[package]
name = "osheep-pty"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
osheep-contract = { path = "../osheep-contract" }
portable-pty.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true
